plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.27.0'
    testImplementation group: 'org.testng', name: 'testng', version: '7.10.2'
    implementation group: 'io.cucumber', name: 'cucumber-java', version: '7.20.1'
    testImplementation group: 'io.cucumber', name: 'cucumber-junit', version: '7.20.1'
//    testImplementation 'io.cucumber:cucumber-java:7.20.1'
//    testImplementation 'io.cucumber:cucumber-spring:7.20.1'

}

test {
    useJUnitPlatform()

    filter {
        // Ini akan memaksa Gradle mencari file Runner kamu
        includeTestsMatching "*CucumberRunner"
    }
}