name: Java Gradle Automation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-gradle-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle' # Mengunci cache library agar build lebih cepat

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Cucumber Tests
        run: |
            ./gradlew test

      - name: Upload Test Report
        if: always() # Baris ini penting agar report tetap di-upload meski test gagal
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: build/reports/tests/test/

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
